front_end/20210930_I3code/TA42-5120/Controllers/DamTreController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace TA42_5120.Controllers
{
    public class DamTreController : Controller
    {
        public ActionResult DamTre()
        {
            ViewBag.Title = "Damage and Treament";
            return View();
        }

        public ActionResult NewSkinDmg()
        {
            ViewBag.Title = "Damage to skin";
            return View();
        }

        public ActionResult Eyedamage()
        {
            ViewBag.Title = "Damage to eyes";
            return View();
        }

        public ActionResult Skindamage()
        {
            ViewBag.Title = "Sunburn damage";
            return View();
        }

        [HttpPost]
        public ActionResult Treatment(string aaa)
        {
            ViewBag.Title = "Sunburn's treatment";
            string urlAddress = "https://lemonumbrella.azurewebsites.net/nearby_hospitals_i2?postcode=" + aaa;
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(urlAddress);
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            if (response.StatusCode == HttpStatusCode.OK)
            {
                Stream receiveStream = response.GetResponseStream();
                StreamReader readStream = null;
                if (response.CharacterSet == null)
                    readStream = new StreamReader(receiveStream);
                else
                    readStream = new StreamReader(receiveStream, Encoding.GetEncoding(response.CharacterSet));
                string data = readStream.ReadToEnd();
                response.Close();
                readStream.Close();
                ViewBag.Markers = data;

                return PartialView("Treatment");
            }
            return null;
        }

        [HttpGet]
        public ActionResult Treatment()
        {
            ViewBag.Title = "Sunburn's treatment";
            return View();
        }
    }
}

front_end/20210930_I3code/TA42-5120/Views/DamTre/DamTre.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Material Design for Bootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet" />
    <!-- MDB -->
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>
<body style="margin-top: 88px !important">

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('../assets/img/treatmentintro.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-10 col-xl-10">
                    <div class="page-heading">
                        <h1>Sunburn damage and treatment</h1>
                        <br />
                        <span class="subheading">Some general sunburn treatment suggestions for children and teenagers</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!--Main layout-->
    <main class="my-5">
        <div class="container">
            <!--Section: Content-->
            <section class="text-center">
                
                <div class="row">
                    <div class="col-lg-6 mb-4">
                        <div class="card">
                            <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                <img src="~/assets/img/eyes.jpg" class="img-fluid"   style="height: 175px; width: 500px;"/>
                                <a href="@Url.Action("Eyedamage", "DamTre")">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                </a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Damage to eyes</h5>
                                <p class="card-text">
                                    Click here and learn more about sunburn damage to eyes
                                </p>
                                <a href="@Url.Action("Eyedamage", "DamTre")" class="btn btn-primary">Learn more</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 mb-4">
                        <div class="card">
                            <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                <img src="~/assets/img/sunburnDam.jpg" class="img-fluid" style="height: 175px; width: 500px;" />
                                <a href="@Url.Action("Skindamage", "DamTre")">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                </a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Sunburn damage</h5>
                                <p class="card-text">
                                    Want to know more about sunburn damage? Click here.
                                </p>
                                <a href="@Url.Action("Skindamage", "DamTre")" class="btn btn-primary">Learn more</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6 mb-4">
                        <div class="card">
                            <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                <img src="~/assets/img/SunburnHead.jpg" class="img-fluid" style="height: 190px; width: 500px;" />
                                <a href="@Url.Action("NewSkinDmg", "DamTre")">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                </a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Damage to skin</h5>
                                <p class="card-text">
                                    Click here and learn more about sunburn damage to skin.
                                </p>
                                <a href="@Url.Action("NewSkinDmg", "DamTre")" class="btn btn-primary">Learn more</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 mb-4">
                        <div class="card">
                            <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                <img src="~/assets/img/treatHead.jpg" class="img-fluid" width=500 height=500 />
                                <a href="@Url.Action("treatment", "DamTre")">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                </a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Treatment</h5>
                                <p class="card-text">
                                    Want to get some general advice about how to treat sunburn? Click here.
                                </p>
                                <a href="@Url.Action("treatment", "DamTre")" class="btn btn-primary">Learn more</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--Section: Content-->
        </div>
    </main>
    <!--Main layout-->
</body>
</html>

front_end/20210930_I3code/TA42-5120/Views/DamTre/NewSkinDmg.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Skin Damage</title>

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
    <link href="~/Content/TA42CommonCSS.css" rel="stylesheet" />

    <style>
      

        .skinPic {
            padding: 5px;
        }

        .headBG {
            background-image: url('../../assets/img/skinHead.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
            height: 300px;
            color: #ffc107;
        }

        .modal-content {
            width: 850px;
        }
        body {
            margin-top: 84px !important;
        }

        .centerP {
            margin-left: auto;
            margin-right: auto;
        }
    </style>

</head>

<body style="margin-top: 84px !important">
    <div class="container-fluid">
        <div class="row" id="top">
            <div class="headBG shadow-2-strong carousel-item active">
                <div class="mask" style="background-color: rgba(0, 0, 0, 0.5);">
                    <div class="d-flex justify-content-center align-items-center">
                        <div class="text-center center">
                            <h2>
                                Protecting your skin Today
                            </h2>
                            <br>
                            <h4>to help avoid Cancer in the Future. </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Section: Design block -->
    <section>
        <div class="container">
            <div class="row d-flex justify-content-center mt-5">
                <div class="col-lg-10">
                    <div class="card mb-2">
                        <div class="card-body p-5">
                            <div class="w3-content w3-display-container">
                                <div class='mySlides'>
                                    <h3 id="what">Why is Ultraviolet radiation (UVR) dangerous?</h3>
                                    <div class="leftB">
                                        <p>UVR is comprised of UVA and UVB rays</p>
                                        <p>UVA can deeply penetrate the skin and cause damages, such as wrinkling or blotchiness. UVA also suppresses our immune system.</p>
                                        <p>UVB penetrates the top layer of the skin and causes sunburn, which could further lead to skin cancer.</p>
                                    </div>
                                    <img src="~/assets/img/skin_uva&uvb.jpg" class="img-fluid centerP" style="width:70%; margin-left:80px;" />
                                    <p class="cite">
                                        Picture retrieved from:
                                        <a href="https://1pgozz2wgm3s1zpozx1y808b-wpengine.netdna-ssl.com/wp-content/uploads/uv-penetration-into-layers-of-the-skin.jpg" target="_blank">
                                            UV penetration into layers of the skin
                                        </a>
                                    </p>
                                </div>

                                <div class='mySlides'>
                                    <h3 id="what">Visible Consequences</h3>
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sm-7">
                                                <div class="leftB">
                                                    <p>Frequent exposure to intense sunlight could cause premature aging of the skin as it becomes thicker and has wrinkles.</p>
                                                    <p><b>Up to 90%</b> of the visible skin aging changes are caused by the interaction with sunlight. With proper protection from UV radiation, most premature aging of the skin <b>can be avoided</b>.</p>
                                                </div>
                                            </div>
                                            <div class="col-sm-5">
                                                <br />
                                                <h5>Premature aging of the skin</h5>
                                                <img src="~/assets/img/skin_Prematured_Aging.jpg" class="img-fluid" />
                                                <p class="cite">
                                                    Picture retrieved from:
                                                    <a href="https://cdn1.vectorstock.com/i/1000x1000/89/90/premature-wrinkles-cosmetology-aging-of-the-skin-vector-16238990.jpg" target="_blank">
                                                        Premature aging
                                                    </a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sm-7">
                                                <div class="leftB">
                                                    <p>If you see unusual skin growths on body areas that are frequently exposed to the sunlight, such as the face, hands, or neck, it could be a sign of skin disorders caused by UVR.</p>
                                                    <p> Those areas could be raised, become red, or have a rough surface and also could <b>increase the risk</b> of having <b>skin cancer</b>.</p>
                                                    <p>In that case, <b>please come and see the doctor as soon as possible</b>.</p>
                                                </div>
                                            </div>

                                            <div class="col-sm-5">
                                                <br /><br />
                                                <h5>Rough skin</h5>
                                                <img src="~/assets/img/skin_rough_skin.jpeg" class="img-fluid" />
                                                <p class="cite">
                                                    Picture retrieved from:
                                                    <a href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvdmZ1zzuXswU3RsBZG_T8ne1blZqgE9bX_g&usqp=CAU" target="_blank">
                                                        Rough skin
                                                    </a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class='mySlides'>
                                    <h3 id="Types">Severe Consequences</h3>
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-md-9">
                                                <div class="leftB">
                                                    <p><b>Melanoma</b> is a type of skin cancer that could be caused by UVR. It is one of the most common cancers <b>among young people aging from 15 to 29</b>. </p>
                                                    <p>UV exposure and sunburns, particularly during childhood, <b>increases the risk</b> of having this disease.</p>
                                                </div>
                                                <div class="leftB">
                                                    <p><b>Basal Cell Carcinomas</b> is a type of skin cancer that could be caused by UVR.</p>
                                                    <p>With this condition, <b>small and fleshy bumps</b> would appear on the <b>head or neck</b> before slowly growing larger. Those bumps could <b>penetrate to the bone</b> and cause significant damages.</p>
                                                </div>
                                                <div class="leftB">
                                                    <p><b>Squamous Cell Carcinomas</b> is similar to Basal Cell Carcinomas as red and scaly patches appear and spread on <b>multiple parts of the body</b>.</p>
                                                </div>

                                                <button class="carosel_button" id="gen_button">How UVR damages the DNA</button>
                                                <div id="gen_modal" class="modal">
                                                    <div class="modal-content">
                                                        <span class="close" id="close_gen">&times;</span>
                                                        <p><b>How UVR damages the DNA</b></p>
                                                        <img src="~/assets/img/dna.jpg" alt="First-aid Treatement to sunburn" class="skinPic centerP" style="width:100%;"><br>
                                                        <p class="cite" style="text-align: left;">
                                                            Retrieve from:
                                                            <a href="https://www.cancercouncil.com.au/wp-content/uploads/2020/08/UV-damages-DNA-1024x633.jpg" target="_blank">Statistics on skin cancer in Australia</a>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <img src="~/assets/img/cancerstat.png" alt="First-aid Treatement to sunburn" class="skinPic centerP" style="width:100%;"><br>
                                                <p class="cite" style="text-align: left;">
                                                    Retrieve from:
                                                    <a href="https://vivacommunications.com.au/blog/skin-cancer-fact-sheet-australia/" target="_blank">Statistics on skin cancer in Australia</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div id="page_num"></div>
                    <span class="caption text-muted">
                        <button class="carosel_button" onclick="plusDivs(-1)">❮</button>
                        <button class="carosel_button" onclick="plusDivs(1)">❯</button>
                    </span>
                </div>
            </div>
        </div>
    </section>

    <script>
        // Get the buttons
        var gen_button = document.getElementById("gen_button");

        // Get the modal
        var gen_modal = document.getElementById("gen_modal");

        // When the user clicks the button, open the modal
        gen_button.onclick = function () {
            gen_modal.style.display = "block";
        }

        var close_gen = document.getElementById("close_gen");
        close_gen.onclick = function () {
            gen_modal.style.display = "none";
        }


        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == gen_modal) {
                gen_modal.style.display = "none";
            }
        }

        // Carosel
        var slideIndex = 1;
        showDivs(slideIndex);

        function plusDivs(n) { showDivs(slideIndex += n); }

        function currentDiv(n) { showDivs(slideIndex = n); }

        function showDivs(n) {
            var i;
            var pagenum = [];
            var x = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("demo");
            if (n > x.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = x.length }
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" w3-red", "");
            }
            x[slideIndex - 1].style.display = "block";
            pagenum.push(`<p style="text-align:center">Pages: ${slideIndex}/${x.length}</p>`);
            page_num.innerHTML = pagenum.join('');
            dots[slideIndex - 1].className += " w3-red";
        }</script>
</body>

</html>